#!/usr/bin/bash

set -o nounset
set -o errexit

readonly REPO="{{ cookiecutter.hub_user }}/{{ cookiecutter.repo_name }}"
readonly TAG="$(cat VERSION)"

/usr/bin/docker pull "$REPO:latest"
/usr/bin/docker tag "$REPO:latest" "$REPO:$TAG"
/usr/bin/docker push "$REPO:$TAG"
